spring:
  application:
    name: demo-backend
  datasource:
    name: db_demo
    platform: mysql
    url: jdbc:mysql://localhost:3306/db_demo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 2208
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connectionTestQuery: select 1
      maximum-pool-size: 2
      connection-timeout: 60000